//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.04.27 at 09:34:17 PM MSK 
//


package com.gendb.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NumericTypes.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NumericTypes"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="tinyint"/&gt;
 *     &lt;enumeration value="smallint"/&gt;
 *     &lt;enumeration value="mediumint"/&gt;
 *     &lt;enumeration value="int"/&gt;
 *     &lt;enumeration value="bigint"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "NumericTypes")
@XmlEnum
public enum NumericTypes {

    @XmlEnumValue("tinyint")
    TINYINT("tinyint"),
    @XmlEnumValue("smallint")
    SMALLINT("smallint"),
    @XmlEnumValue("mediumint")
    MEDIUMINT("mediumint"),
    @XmlEnumValue("int")
    INT("int"),
    @XmlEnumValue("bigint")
    BIGINT("bigint");
    private final String value;

    NumericTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NumericTypes fromValue(String v) {
        for (NumericTypes c: NumericTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
